backend:
  name: github
  repo: your-username/your-repo-name  # استبدل بمستودعك على GitHub

# مكان حفظ الصور
media_folder: "images/uploads"      # المجلد الذي تُحفظ فيه الصور
public_folder: "/images/uploads"   # المسار العام للصور في الموقع

# الأقسام التي سيتم إدارتها
collections:
  - name: "services"               # اسم المجموعة (مثال: "الخدمات")
    label: "الخدمات"               # الاسم الظاهر في الواجهة
    folder: "_data/services"       # مجلد حفظ البيانات (سيُنشئه تلقائيًا)
    create: true                   # يسمح بإنشاء محتوى جديد
    fields:                        # الحقول التي يمكن تعديلها
      - { name: "title", label: "العنوان", widget: "string" }
      - { name: "description", label: "الوصف", widget: "text" }
      - { name: "image", label: "صورة", widget: "image" }